from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField
import os

class choose_form(FlaskForm):
    # https://teamtreehouse.com/community/using-wtforms-for-selectfield-in-flask
    target = [("GDP growth","GDP growth"),("Interest rate","Ineterst rate")]
    target_indicator = SelectField('Please select indicator', choices=target)
    submit = SubmitField('Submit')

class new_form(FlaskForm):
    target = [("Aruba","ABW"),("Afghanistan","AFG"),("Africa","AFR"),("Albania","ALB"),("Algeria","DZA"),("American Samoa","ASM"),("Andean Region","ANR"),("Andorra","AND"),("Angola","AGO"),("Antigua and Barbuda","ATG"),("Arab World","ARB"),("Argentina","ARG"),("Armenia","ARM"),("Australia","AUS"),("Austria","AUT"),("Azerbaijan","AZE"),
    ("Bahamas, The","BHS"),("Bahrain","BHR"),("Bangladesh","BGD"),("Barbados","BRB"),("Belarus","BLR"),("Belgium","BEL"),("Belize","BLZ"),("Benin","BEN"),("Bermuda","BMU"),("Bhutan","BTN"),("Bolivia","BOL"),("Bosnia and Herzegovina","BIH"),("Botswana","BWA"),("Brazil","BRA"),("British Virgin Islands","VGB"),("Brunei Darussalam","BRN"),("Bulgaria","BGR"),("Burkina Faso","BFA"),("Burundi","BDI"),
    ("Cabo Verde","CPV"),("Cambodia","KHM"),("Cameroon","CMR"),("Canada","CAN"),("Caribbean small states","CSS"),("Cayman Islands","CYM"),("Central African Republic","CAF"),("Central America","MCA"),("Central Europe and the Baltics","CEB"),("Chad","TCD"),("Channel Islands","CHI"),("Chile","CHL"),("China","CHN"),("Colombia","COL"),("Comoros","COM"),("Congo, Dem. Rep.","COD"),("Congo, Rep.","COG"),("Costa Rica","CRI"),("Cote d'Ivoire","CIV"),("Croatia","HRV"),("Cuba","CUB"),("Curacao","CUW"),("Cyprus","CYP"),("Czech Republic","CZE"),
    ("Denmark","DNK"),("Djibouti","DJI"),("Dominica","DMA"),("Dominican Republic","DOM"),("Early-demographic dividend","EAR"),("East Asia & Pacific","EAS"),("East Asia & Pacific (excluding high income)","EAP"),("East Asia & Pacific (IBRD-only countries)","BEA"),("East Asia & Pacific (IDA & IBRD countries)","TEA"),("East Asia & Pacific (IDA-eligible countries)","DEA"),("East Asia and the Pacific (IFC classification)","CEA"),
    ("Ecuador","ECU"),("Egypt, Arab Rep.","EGY"),("El Salvador","SLV"),("Equatorial Guinea","GNQ"),("Eritrea","ERI"),("Estonia","EST"),("Eswatini","SWZ"),("Ethiopia","ETH"),("Euro area","EMU"),("Europe & Central Asia","ECS"),("Europe & Central Asia (excluding high income)","ECA"),("Europe & Central Asia (IBRD-only countries)","BEC"),("Europe & Central Asia (IDA & IBRD countries)","TEC"),("Europe & Central Asia (IDA-eligible countries)","DEC"),("Europe and Central Asia (IFC classification)","CEU"),("European Union","EUU"),
    ("Faroe Islands","FRO"),("Fiji","FJI"),("Finland","FIN"),("Fragile and conflict affected situations","FCS"),("France","FRA"),("French Polynesia","PYF"),
    ("Gabon","GAB"),("Gambia, The","GMB"),("Georgia","GEO"),("Germany","DEU"),("Ghana","GHA"),("Gibraltar","GIB"),("Greece","GRC"),("Greenland","GRL"),("Grenada","GRD"),("Guam","GUM"),("Guatemala","GTM"),("Guinea","GIN"),("Guinea-Bissau","GNB"),("Guyana","GUY"),
    ("Haiti","HTI"),("Heavily indebted poor countries (HIPC)","HPC"),("High income","HIC"),("Honduras","HND"),("Hong Kong SAR, China","HKG"),("Hungary","HUN"),
    ("IBRD countries classified as high income","BHI"),("IBRD only","IBD"),("IBRD, including blend","IBB"),("Iceland","ISL"),("IDA & IBRD total","IBT"),("IDA blend","IDB"),("IDA countries classified as Fragile Situations","DFS"),("IDA countries classified as fragile situations, excluding Sub-Saharan Africa","FXS"),("IDA countries in Sub-Saharan Africa classified as fragile situations ","DSF"),("IDA countries in Sub-Saharan Africa not classified as fragile situations ","DNS"),("IDA countries not classified as Fragile Situations","DNF"),("IDA countries not classified as fragile situations, excluding Sub-Saharan Africa","NXS"),("IDA only","IDX"),("IDA total","IDA"),("IDA total, excluding Sub-Saharan Africa","DXS"),("India","IND"),("Indonesia","IDN"),("Iran, Islamic Rep.","IRN"),("Iraq","IRQ"),("Ireland","IRL"),("Isle of Man","IMN"),("Israel","ISR"),("Italy","ITA"),
    ("Jamaica","JAM"),("Japan","JPN"),("Jordan","JOR"),
    ("Kazakhstan","KAZ"),("Kenya","KEN"),("Kiribati","KIR"),("Korea, Dem. People’s Rep.","PRK"),("Korea, Rep.","KOR"),("Kosovo","XKX"),("Kuwait","KWT"),("Kyrgyz Republic","KGZ"),
    ("Lao PDR","LAO"),("Late-demographic dividend","LTE"),("Latin America & Caribbean ","LCN"),("Latin America & Caribbean (excluding high income)","LAC"),("Latin America & the Caribbean (IBRD-only countries)","BLA"),("Latin America & the Caribbean (IDA & IBRD countries)","TLA"),("Latin America & the Caribbean (IDA-eligible countries)","DLA"),("Latin America and the Caribbean","LCR"),("Latin America and the Caribbean (IFC classification)","CLA"),("Latvia","LVA"),("Least developed countries: UN classification","LDC"),("Lebanon","LBN"),("Lesotho","LSO"),("Liberia","LBR"),("Libya","LBY"),("Liechtenstein","LIE"),("Lithuania","LTU"),("Low & middle income","LMY"),("Low income","LIC"),("Lower middle income","LMC"),("Luxembourg","LUX"),
    ("Macao SAR, China","MAC"),("Madagascar","MDG"),("Malawi","MWI"),("Malaysia","MYS"),("Maldives","MDV"),("Mali","MLI"),("Malta","MLT"),("Marshall Islands","MHL"),("Mauritania","MRT"),("Mauritius","MUS"),("Mexico","MEX"),("Micronesia, Fed. Sts.","FSM"),("Middle East (developing only)","MDE"),("Middle East & North Africa","MEA"),("Middle East & North Africa (excluding high income)","MNA"),("Middle East & North Africa (IBRD-only countries)","BMN"),("Middle East & North Africa (IDA & IBRD countries)","TMN"),("Middle East & North Africa (IDA-eligible countries)","DMN"),("Middle East and North Africa (IFC classification)","CME"),("Middle income","MIC"),("Moldova","MDA"),("Monaco","MCO"),("Mongolia","MNG"),("Montenegro","MNE"),("Morocco","MAR"),("Mozambique","MOZ"),("Myanmar","MMR"),
    ("Namibia","NAM"),("Nauru","NRU"),("Nepal","NPL"),("Netherlands","NLD"),("New Caledonia","NCL"),("New Zealand","NZL"),("Nicaragua","NIC"),("Niger","NER"),("Nigeria","NGA"),("Non-resource rich Sub-Saharan Africa countries","NRS"),("Non-resource rich Sub-Saharan Africa countries, of which landlocked","NLS"),("North Africa","NAF"),("North America","NAC"),("North Macedonia","MKD"),("Northern Mariana Islands","MNP"),("Norway","NOR"),("Not classified","INX"),
    ("OECD members","OED"),("Oman","OMN"),("Other small states","OSS"),
    ("Pacific island small states","PSS"),("Pakistan","PAK"),("Palau","PLW"),("Panama","PAN"),("Papua New Guinea","PNG"),("Paraguay","PRY"),("Peru","PER"),("Philippines","PHL"),("Poland","POL"),("Portugal","PRT"),("Post-demographic dividend","PST"),("Pre-demographic dividend","PRE"),("Puerto Rico","PRI"),
    ("Qatar","QAT"),("Resource rich Sub-Saharan Africa countries","RRS"),("Resource rich Sub-Saharan Africa countries, of which oil exporters","RSO"),("Romania","ROU"),("Russian Federation","RUS"),("Rwanda","RWA"),("Samoa","WSM"),
    ("San Marino","SMR"),("Sao Tome and Principe","STP"),("Saudi Arabia","SAU"),("Senegal","SEN"),("Serbia","SRB"),("Seychelles","SYC"),("Sierra Leone","SLE"),("Singapore","SGP"),("Sint Maarten (Dutch part)","SXM"),("Slovak Republic","SVK"),("Slovenia","SVN"),("Small states","SST"),("Solomon Islands","SLB"),("Somalia","SOM"),("South Africa","ZAF"),("South Asia","SAS"),("South Asia (IDA & IBRD)","TSA"),("South Asia (IDA-eligible countries)","DSA"),("South Asia (IFC classification)","CSA"),("South Sudan","SSD"),("Southern Cone","SCE"),("Spain","ESP"),("Sri Lanka","LKA"),("St. Kitts and Nevis","KNA"),("St. Lucia","LCA"),("St. Martin (French part)","MAF"),("St. Vincent and the Grenadines","VCT"),("Sub-Saharan Africa ","SSF"),("Sub-Saharan Africa (excluding high income)","SSA"),("Sub-Saharan Africa (IBRD-only countries)","BSS"),("Sub-Saharan Africa (IDA & IBRD countries)","TSS"),("Sub-Saharan Africa (IDA-eligible countries)","DSS"),("Sub-Saharan Africa (IFC classification)","CAA"),("Sub-Saharan Africa excluding South Africa","SXZ"),("Sub-Saharan Africa excluding South Africa and Nigeria","XZN"),("Sudan","SDN"),("Suriname","SUR"),("Sweden","SWE"),("Switzerland","CHE"),("Syrian Arab Republic","SYR"),
    ("Taiwan, China","TWN"),("Tajikistan","TJK"),("Tanzania","TZA"),("Thailand","THA"),("Timor-Leste","TLS"),("Togo","TGO"),("Tonga","TON"),("Trinidad and Tobago","TTO"),("Tunisia","TUN"),("Turkey","TUR"),("Turkmenistan","TKM"),("Turks and Caicos Islands","TCA"),("Tuvalu","TUV"),
    ("Uganda","UGA"),("Ukraine","UKR"),("United Arab Emirates","ARE"),("United Kingdom","GBR"),("United States","USA"),("Upper middle income","UMC"),("Uruguay","URY"),("Uzbekistan","UZB"),
    ("Vanuatu","VUT"),("Venezuela, RB","VEN"),("Vietnam","VNM"),("Virgin Islands (U.S.)","VIR"),
    ("West Bank and Gaza","PSE"),("World","WLD"),
    ("Yemen, Rep.","YEM"),
    ("Zambia","ZMB"),("Zimbabwe","ZWE")]
