import os

from flask import current_app, render_template, jsonify
from flask_sqlalchemy import SQLAlchemy
from app.saving import bp
import pandas as pd
import altair as alt

# urls for isioln storage
@bp.route('/')
@bp.route('/index', methods=['GET','POST'])
def index():
    print("index")
    """
    Base URL for the table folder
    """
    return render_template('saving/index.html')

@bp.route('/saving_JSON')
def savings_JSON():
    """
    A JSON format of a csv file of best savings rates in the UK (https://www.moneysavingexpert.com/savings/savings-accounts-best-interest/)
    Args:
        csv file
    Returns:
        JSON format datatable
    """
    print("savings json")
    db = pd.read_csv("app/static/saving_rate.csv")
    print(db)
    sumJSON = db.to_json(orient='table',index=False)
    print(sumJSON)
    return sumJSON

# urls for local storage
@bp.route('/graph', methods=['GET','POST'])
def graph():
    """
    Calls the url for viewing the folders within mount (the mount folder)
    Args:
        Two text files 1 with output from stats and another with the output from du
        these are generated by listfile.sh
    Returns:
        Calls the correct url and calculates total space used, percentage of total available 
        and the time the du and stat command were done
    """
    return render_template('saving/graph.html')

@bp.route('/saving_chart')
def saving_chart():
    df = pd.read_csv("app/static/saving_rate.csv")
    chart =  alt.Chart(df,
    width=500,
    height=400    
    ).mark_bar().encode(
        x="PROVIDER",
        y='RATE',
        color=alt.Color('PROVIDER', scale=alt.Scale(scheme='dark2'))
        ).properties(
        title='Best Instant Access Savings Rates'
        ).configure_axis(
        labelFontSize=15,
        titleFontSize=15
        ).configure_legend( 
        gradientLength=600, 
        gradientThickness=60
        )
    return chart.to_json()
